# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Maxime Dumont
title: Ingénieur agronome et docteur en télédétection pour les sciences de l'environnement
email: maxime.dumont96@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: mxDumont
orcid_username: 0000-0002-2033-7853

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Je suis un ingénieur agronome et docteur en télédétection, passionné par l'application des outils numériques aux problématiques environnementales. Créatif, rigoureux et motivé, je combine expertise technique et compétences en gestion de projet pour répondre aux défis environnementaux.

  Mes domaines de prédilection incluent : <mark>Télédétection</mark>, <mark>statistiques avancées</mark> et <mark>programmation</mark>.

content:
  - title: Expériences professionnelles
    layout: list
    content:
      - layout: left
        title: Valorhiz & L'Institut Agro Montpellier
        link: https://valorhiz.com
        sub_title: Doctorant en contrat CIFRE
        caption: 2022 - Présent
        quote: >
          Constitution d'une base d'apprentissage guidée par des expertises métiers pour améliorer les méthodes de classification de l'occupation des sols.
        description: |
          - Machine Learning et modélisation en télédétection
          - Développement en Python et statistiques spatiales
          - Méthodes d'échantillonnage et communication scientifique

      - layout: left
        title: Valorhiz
        sub_title: Stage de fin d'études
        caption: Mars - Septembre 2021
        quote: >
          Segmentation d’ortho-images pour le suivi de l’occupation des sols.
        description: |
          - Machine Learning appliqué à la télédétection
          - Formation aux enjeux agro-environnementaux

      - layout: left
        title: INRAE UMR ABSYS
        sub_title: Stage de recherche
        caption: Septembre 2019 - Février 2020
        quote: >
          Analyse pédoclimatique et étude statistique de l'influence du climat sur le rendement viticole.
        description: |
          - Enquêtes terrain et analyse de données à grande échelle
          - Publication d’un article scientifique

  - title: Formation
    layout: list
    content:
      - layout: left
        title: Doctorat en télédétection
        caption: 2022 - 2025
        sub_title: Valorhiz & L'Institut Agro Montpellier

      - layout: left
        title: Diplôme d’ingénieur agronome - Spécialité Agrotic
        caption: 2017 - 2021
        sub_title: Bordeaux Sciences Agro
        description: |
          - Formation transversale : agronomie et numérique
          - Techniques statistiques et relevés terrain

      - layout: left
        title: Classe préparatoire BCPST
        caption: 2014 - 2017
        sub_title: Lycée Chaptal, Paris

      - layout: left
        title: Semestre d'échange
        caption: Août - Décembre 2018
        sub_title: Universidade Federal de Santa Catarina, Brésil
        description: |
          - Découverte culturelle et apprentissage du portugais
          - Étude des techniques agronomiques en climat subtropical

  - title: Compétences
    layout: text
    content: |
      - Télédétection et Machine Learning
      - Programmation : R, Python
      - Systèmes d’exploitation : Windows, Ubuntu, MacOS
      - Gestion de projet et rédaction scientifique
      - Langues :
        - Anglais : C1 (TOEIC 930)
        - Portugais : B2
        - Espagnol : B1

  - title: Prix et distinctions
    layout: list
    content:
      - layout: left
        title: Best Poster Presentation
        sub_title: Soil Mapping for a Sustainable Future Conference, Orléans
        caption: Février 2023

      - layout: left
        title: Best Oral Presentation
        sub_title: EuroLeague for Life Science Student Conference, Stuttgart
        caption: Novembre 2023

  - title: Centres d’intérêts
    layout: text
    content: |
      - Randonnée, vélo et escalade
      - Musique : guitare, chant, production musicale
      - Cuisine et voyage en mobilités douces
