# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Maxime Dumont
title: PhD in Remote Sensing for Environmental Sciences
email: maxime.dumont96@gmail.com
website: www.github.com/mxDumont

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: mxDumont
linkedin_username: maxime-dumont-945bb2164
orcid_username: 0000-0002-2033-7853

# Additional icon links
additional_links:
- title: My ResearchGate
  icon: fas fa-globe
  url: https://www.researchgate.net/profile/Maxime-Dumont-5

# About Section
about_profile_image: images/autocollant-psykokwak-pokemon-054.png
about_content: | # this will include new lines to allow paragraphs
  Hello! I’m Maxime, a PhD in remote sensing with a passion for solving environmental challenges using digital tools and advanced statistical methods. I specialize in machine learning, spatial statistics, and remote sensing.

  I'd say im : <mark>Curious</mark>, <mark>Creative</mark>, and <mark>Rigorous</mark> plus <mark style="background-color: #deb452; color: black;">zozo </mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Soil Mapping for a Sustainable Future
        link: github.com/mxDumont/soil-mapping
        additional_links:
          - title:  mxDumont/soil-mapping
            icon: fab fa-github
            url: github.com/mxDumont/soil-mapping
        quote: >
          Innovative research on improving soil mapping methods using advanced machine learning.
        description: | # this will include new lines to allow paragraphs
          This project focuses on utilizing remote sensing techniques for soil mapping, aiming to improve accuracy and sustainability. It includes statistical modeling, data analysis, and collaborations with research institutions.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Valorhiz & L’Institut Agro Montpellier
        link: https://valorhiz.com
        sub_title: PhD Student in Remote Sensing
        caption: February 2022 - Present
        quote: >
          Developing data-driven solutions for soil and land use classification.
        description: | # this will include new lines to allow paragraphs
          - Conducted research on machine learning for land-use classification
          - Developed Python tools for spatial statistics and sampling
          - Presented findings at international conferences

      - layout: left
        title: Valorhiz
        sub_title: Final-Year Internship
        caption: March - September 2021
        quote: >
          Segmentation of ortho-images for land cover monitoring.
        description: | # this will include new lines to allow paragraphs
          - Applied machine learning techniques to remote sensing data
          - Analyzed the environmental impact of land use changes

      - layout: left
        title: INRAE UMR ABSYS
        sub_title: Research Internship
        caption: September 2019 - February 2020
        quote: >
          Statistical analysis of climate impact on viticulture in Languedoc-Roussillon.
        description: | # this will include new lines to allow paragraphs
          - Conducted pedoclimatic analysis and large-scale surveys
          - Published research on climate influence on vineyard yields

  - title: Education
    layout: list
    content:
      - layout: left
        title: PhD in Remote Sensing
        caption: 2022 - 2025
        sub_title: Valorhiz & L’Institut Agro Montpellier

      - layout: left
        title: MSc in Agrotic Engineering
        caption: 2017 - 2021
        sub_title: Bordeaux Sciences Agro
        description: |
          - Specialized in agricultural technologies and data science
          - Completed courses in statistics, GIS, and remote sensing

      - layout: left
        title: Exchange Semester
        caption: August - December 2018
        sub_title: Universidade Federal de Santa Catarina, Brazil
        description: |
          - Studied agricultural techniques in a subtropical climate
          - Gained fluency in Portuguese

      - layout: left
        title: BCPST Preparatory Classes
        caption: 2014 - 2017
        sub_title: Lycée Chaptal, Paris

  - title: Skills
    layout: text
    content: |
      - Remote Sensing and Machine Learning
      - Programming: Python, R
      - Statistical Modeling and Spatial Analysis
      - Fluent in English (C1), Portuguese (B2), and Spanish (B1)
      - Operating Systems: Windows, Ubuntu, macOS

  - title: Awards
    layout: list
    content:
      - layout: left
        title: Best Poster Presentation
        sub_title: Soil Mapping for a Sustainable Future Conference, Orléans
        caption: February 2023

      - layout: left
        title: Best Oral Presentation
        sub_title: EuroLeague for Life Sciences Student Conference, Stuttgart
        caption: November 2023

  - title: Interests
    layout: text
    content: |
      - Hiking, cycling, and rock climbing
      - Playing guitar, singing, and music production
      - Traveling with a focus on eco-friendly mobility

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
